::Raids.Strings.Lairs.Traits <-
{
	AssassinsLeagueName = "League of Assassins",
	AvariciousName = "Avaricious",
	BanditExilesName = "Brigand Exiles",
	BeastlyKennelName = "Beastly Kennel",
	CultistsName = "Cultists",
	EnthralledMassesName = "Enthralled Masses",
	HeroesGraveyardName = "Graveyard of Heroes",
	HolyCongregationName = "Holy Congregation",
	HiredHandsName = "Hired Hands",
	MarksmenName = "Marksmen",
	MarksmenSouthernName = "Marksmen",
	MercenaryKnightsName = "Mercenary Knights",
	NecromancyName = "Necromancy",
	NobleDesertersName = "Deserters",
	NobleDesertersSouthernName = "Deserters",
	NorthernExilesName = "Northern Exiles",
	OrcAllianceName = "Orc Alliance",
	PeasantRevoltName = "Peasant Revolt",
	PeasantRevoltSouthernName = "Peasant Revolt",
	RenegadeMilitiaName = "Renegade Militia",
	RoguesCoterieName = "Coterie of Rogues",
	SlaveRevoltName = "Slave Revolt",
	SubjugatedGoblinsName = "Subjugated Goblins",
	SouthernExilesName = "Southern Exiles",
	SwordmastersKeepName = "Swordmasters' Keep",
	TamedDirewolvesName = "Tamed Direwolves",
	TamedHyenasName = "Tamed Hyenas",
	TamedSerpentsName = "Tamed Serpents",
	UndeadVanguardName = "Undead Vanguard",
	VampiricBroodName = "Vampiric Brood",
	WitchesCovenName = "Coven of Witches"
};